app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


# user class
class User(UserMixin,db.Model):

    '''
    User class to define user Objects
    '''
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    #ROLES
    # is_active = db.Column(db.Boolean,default=False)
    # urole = db.Column(db.String(80))


    
    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    # def get_id(self):
    #         return self.id
    # def is_active(self):
    #         return self.is_active
    # def activate_user(self):
    #         self.is_active = True         
    # def get_username(self):
    #         return self.username
    # def get_urole(self):
            # return self.urole

    def __repr__(self):
        return f'User {self.username}'



class Mech(UserMixin,db.Model):

    '''
    Mechanics class to define mechanic Objects
    '''
    __tablename__ = 'mechanics'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    # password_hash = db.Column(db.String(255))
    role = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    specialization = db.Column(db.String(255), index = True,nullable = False)
    

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'Mech {self.username}'


class Formfield(db.Model):
    __tablename__ = 'formfields'
    id = db.Column(db.Integer, primary_key = True)
    query = db.Column(db.String(255))
    time_posted = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_queries(self):
        """
        Save the queries
        """
        db.session.add(self)
        db.session.commit()

    # @classmethod
    # def get_queries(id):
    #     queries = Formfield.query.filter_by(post_id=id).all()
    #     return queries



class Display(db.Model):
    __tablename__ = "displays"

    id = db.Column(db.Integer, primary_key = True)
    display = db.Column(db.String)
    dispalyed_at = db.Column(db.DateTime)
    dispalyed_by = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    formfield_id = db.column(db.Integer, db.ForeignKey("formfield_id"))

    def save_display(self):
        db.session.add(self)
        db.session.commit()


    @classmethod
    def get_comments(cls, id):
        display= Display.query.filter_by(formfield_id = id).all()
        return display

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, TextAreaField,
                    SubmitField, SelectField)
from wtforms.validators import Required


class userForm(FlaskForm):
    first_name = StringField("First name")
    last_name = StringField("Last Name")
    queries = TextAreaField("Queries")
    email = StringField("Email")
    submit = SubmitField("submit")


class queriesForm(FlaskForm):
      """
      Class to create a wtf form for adding a car defect
      """
      query = TextAreaField('Car Defect:')
      submit = SubmitField('SUBMIT')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_simplemde import SimpleMDE
from flask_mail import Mail



bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()
simple = SimpleMDE()


photos = UploadSet('photos', IMAGES)


def create_app(config_name):
    app = Flask(__name__)
    mail.init_app(app)
    print(mail)
    simple.init_app(app)
    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # Initializing Flask Extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint

    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')


    # configure UploadSet
    configure_uploads(app, photos)



    return app
from .main import views

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,error, forms

app/main/views.py
from app.main.forms import queriesForm
from flask import render_template, request, redirect, url_for
from flask.helpers import flash
from . import main
from .. import db
from ..models import User, Formfield,Display
from flask_login import login_required, current_user
from datetime import datetime
# from ..request import get_quote
from ..email import mail_message


# 1 the main index(default)
@main.route("/", methods=["GET", "POST"])
def index():

       

        return render_template('index.html')

# @main.route('/',methods = ['GET' , 'POST'])
# def queries():
#         queries = Formfield()

#         return  render_template('queries.html',queries=queries)











@main.route('/newqueries',methods = ['GET' , 'POST'])
def new_query():

    queries_form = queriesForm()
    if  queries_form.validate_on_submit():
        query = queries_form.query.data
        new_query = Formfield(query=query)
        db.session.add(new_query)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('new_queries.html',queries_form = queries_form)


@main.route("/display/<int:id>", methods = ["POST", "GET"])
def Displayqueries(formfield_id):
    formfield = Formfield.filter_by(formfield_id=formfield_id).all()
    display = Display.query.filter_by(post_id=formfield_id).all()
    queries_Form= queriesForm()
    if queries_Form.validate_on_submit():
        display = queries_Form.problem.data
        new_query = Display(post_id=formfield_id,display=display)
        new_query.save_display()
    return render_template('display_queries.html', formfield=formfield, display=display, queries_Form=queries_Form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}

{% endblock %}
<!-- styles -->
{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/display.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro %}


{% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500&display=swap" rel="stylesheet">
<div class="container">
    <h3 class="text-center text-uppercase" style="color:navy">Display Mech</h3>

    <div class="row">

        <h3> Found {{ spec| count }} matches </h3>
        <hr>
        <ul>
            {{ macro.displayMechanic(spec)}}
        </ul>

    </div>
</div>

{% endblock %}

app/templates/forms.html
{% extends "base.html" %}
{% import "forms.html" as forms %}

{% block content %}
{{ forms.render(form) }}
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
<p>hello, welcome to auto mech</p>
{% if current_user.is_authenticated %}
<a href="{{url_for( 'main.new_query')}}">QUERIES</a>
{%endif%}
{%endblock%}

app/templates/macros.html
{%macro displayMechanic(mech_list)%}
{%for mech in mech_list%}
<style>
    img {
        border-radius: 50%;
    }

    #outer-div {
        text-align: center;
        padding-top: 3%;

    }

    #inner-div {
        display: inline-block;
        margin: 0 auto;
    }

    .mech-info {
        /* text-align: left; */
        border-radius: 2%;
        box-shadow: 0vh 0vh 3vh rgb(194, 189, 189);
        background-color: rgb(238, 233, 233);
    }
</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500&display=swap" rel="stylesheet">
<div class="col-md-4" id="outer-div" style="font-family: 'Caveat', cursive;">
    <div class="mech-info" style="box-sizing: border-box; padding: 2%;">
        <div class="photo" id="inner-div" style="height: 120px; width: 120px;">

            {%if profile_pic_path == Null%}
            <img src="https://thumbs.dreamstime.com/b/user-icon-vector-male-person-symbol-profile-circle-avatar-sign-flat-color-glyph-pictogram-illustration-user-icon-vector-male-115922552.jpg"
                class="img-responsive" height="100%" width="100%">
            {%else%}
            <img src="profile_pic_path" class="img-responsive" height="100%" width="100%">
            {%endif%}
        </div>
        <p style="font-size:13pt">Name : {{mech.username}}</p>
        <p style="font-size:11pt"> From : {{mech.location}}</p>
        
      
        <p>Specialization: {{mech.specialization}}</p>
        <a href="{{url_for('main.mech_profile',uname=mech.username)}}" type="button" style="border: none;"
            class=" btn btn-info d-flex">
            View Profile
        </a>
        
     
        <p class="lorem"></p>
    </div>
</div>
{%endfor%}
{%endmacro%}

app/templates/navbar.html
<style> .navbar {
    background: linear-gradient(0.25turn, #3f87a6, #ebf8e1, #f69d3c);
    border: none;
    border-radius: 0%;
    margin: 0%;
}</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Marck+Script&display=swap" rel="stylesheet">
<div class="navbar navbar-inverse" role="navigation" style="font-family: 'Marck Script', cursive;font-size:20px ;color:blue;">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" style="color:blue;"> AutoMech </a>
        </div>
        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li><a href="/"style="color:blue;">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" >
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.user_profile',uname=current_user.username)}}"style="color:blue;" >user profile</a></li>
                <li><a href="/">{{current_user.username.capitalize()}}</a></li>
                <li><a href="{{url_for('auth.logout')}}" style="color:blue;">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}" style="color:blue;">Sign in</a></li>
                {%endif%}

              </ul>
        </div>

</div>

app/templates/new_queries.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container" style="font-size: 20px; font-family: 'Merienda', cursive;  padding-top: 40px;">
<div class="row">
<div class="col-md-4 mt-3 p-5">
    <h3 class="mt-3 pb-3 text-center">Queries</h3>
    <hr>
{{wtf.quick_form(queries_form)}}


{% endblock%}

app/templates/profile/mech_profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{mech.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if mech.bio %}
    <h2>Bio: </h2>
      <p> {{mech.bio}}</p>
    {%else%}
      <p> {{mech.username| capitalize}} has no bio </p>
    {% endif %}

    {% if mech.specialization %}
    <h2>specialization: </h2>
      <p>{{mech.specialization}}</p>
    {%else%}
      <p> {{mech.username| capitalize}} has no specializations </p>
    {% endif %}

    {% if mech.location %}
    <h2>Location: </h2>
      <p>{{mech.location}}</p>
    {%else%}
      <p> {{mech.username| capitalize}} has not added their location </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if mech.profile_pic_path %}
    <img src="{{url_for('static',filename=mech.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  {% if mech == current_user %}
    <a href="{{url_for('main.update_mech_profile',uname=mech.username)}}">Edit profile</a>
 {% endif %}
 {% if mech == current_user %}
    <form  action="{{url_for('main.update_mech_pic',uname=mech.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
</div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/profile/user_profile.html
{% extends 'base.html'%}

{% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500&display=swap" rel="stylesheet">
<div class="container" style="font-family: 'Caveat', cursive;font-size: 20px;">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
  {% if user == current_user %}
    <a href="{{url_for('main.update_user_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
</div>
</div>
{% endblock %}

app/templates/queries.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
<div class="container">
    <div class="row">
      <div class= "col-md-2"> </div>
      <div class="col-md-8">
      <!--Flash message -->
      {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
        </div>
      {% endfor %}
      <button><a href="/newqueries">addquery</a></button>
      <div class="container">
        {%for query in queries %}
        <p>{{query.query}}</p>
        <p>{{query.time_posted}}</p>
        {% endfor %}

      </div>
     </div>
     <div clas="col-md-2"> </div>
    </div>
</div>
{% endblock%}

app/templates/viewmech.html
{% extends 'base.html'%}

{%block content%}

<style>
    .form-control,
    .btnsub {
        height: 50px;
    }

    .results {
        padding-top: 4%;
    }

    img {
        border-radius: 50%;
    }

    .lorem {
        padding: 3%;

    }

    #outer-div {
        text-align: center;
        padding-top: 3%
    }

    #inner-div {
        display: inline-block;
        margin: 0 auto;
    }

    .mech-info {
        /* text-align: left; */
        border-radius: 2%;
        box-shadow: 0vh 0vh 3vh rgb(194, 189, 189);
        background-color: rgb(238, 233, 233);
    }
</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500&display=swap" rel="stylesheet">
<div class="col-md-12 text-center"
    style="padding: 10%; margin-bottom:3%;width:100%; background-image:url('https://cdn.pixabay.com/photo/2017/02/02/18/16/child-2033444_960_720.jpg');font-family: 'Caveat', cursive; background-repeat:no-repeat; background-position: center; background-size:cover">
    <div class="" style="color:white">
        <h1 style="font-size:50px; font-weight:700">Find Mechanics Closeby</h1>
        <h3>Our mechanics are available for you anywhere at anytime</h3>
    </div>
</div>

<body class="">

    <div class="container">
        <form class="row" action="/search" method=post>
            <div class="col-md-10">
                <div class="col-md-4">
                    <input type="text" name="mech_query" placeholder="Search for a mechanic" class="form-control">
                </div>
                <div class="col-md-4">
                    <input type="text" name="location_query" placeholder="Enter location" class="form-control">
                </div>
                <div class="col-md-4">
                    <input type="text" name="service_query" placeholder="Enter service" class="form-control">
                </div>
            </div>

            <div class="col-md-2">
                <input type="submit" value="Submit" style="border:none;" class="btnsub btn btn-primary col-md-12">
            </div>
        </form>
        <h5 class="results">For best results consider, reviews specialization and experience</h5>
        <hr>
        <h3 class="results">Top Mechanics</h3>
        <h5 style="padding-top:2%">See our top mechanics with great client service</h5>
        <div class="row text-center">
            <div class="col-md-4" id="outer-div">
                <div class="mech-info" style="box-sizing: border-box; padding: 2%;">

                    <div class="photo" id="inner-div" style="height: 120px; width: 120px;">
                        <img src="https://www.artistsandillustrators.co.uk/uploads/tinymce/images/painting-animated-faces-photo.jpg"
                            height="100%" width="100%">
                    </div>
                    <h4>Andrea Kitas</h4>
                    <p class="lorem">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        incididunt ut
                        labore
                        et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
                        ut
                        aliquip ex ea commodo consequat."</p>
                </div>
            </div>

            <div class="col-md-4" id="outer-div">
                <div class="mech-info" style="box-sizing: border-box; padding: 2%;">
                    <div class="photo" id="inner-div" style="height: 120px; width: 120px;">
                        <img src="https://www.headshotsprague.com/wp-content/uploads/2019/07/Headshots_Prague-emotional-portrait-of-a-smiling-entrepreneur-1.jpg"
                            height="100%" width="100%">
                    </div>
                    <h4>Martez Retas</h4>
                    <p class="lorem">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        incididunt ut
                        labore
                        et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
                        ut
                        aliquip ex ea commodo consequat."</p>
                </div>
            </div>
            <div class="col-md-4" id="outer-div">
                <div class="mech-info" style="box-sizing: border-box; padding: 2%;">

                    <div class="photo" id="inner-div" style="height: 120px; width: 120px;">
                        <img src="http://www.robophot.com/wp-content/plugins/widgetkit/cache/gallery/379/002_boehm_andre_130918_test_tiffocsel_no_stackretou_cut_300-6af69709ca.jpg"
                            height="100%" width="100%">
                    </div>
                    <h4>Monte Gonzelez</h4>
                    <p class="lorem">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        incididunt ut
                        labore
                        et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
                        ut
                        aliquip ex ea commodo consequat."</p>
                </div>
            </div>

        </div>


    </div>
    </div>
</body>
{%endblock%}